### ISSUE TITLE
[Chart Generation] 图表生成支持传入VChart主题

### ISSUE THREAD

**Issue by da730** [VisActor/VMind#104]
1. 内置几套常见的VChart主题和图表助手主题：https://www.visactor.io/vchart/theme/playground
2. VMind.generateChart接口，支持传入theme参数
3. 图表生成pipeline将theme应用到图表spec上
4. 修改默认的主题样式

**Comment by MaxtuneLee** [comment]
似乎与目前已有的功能有一部分功能重合
https://github.com/VisActor/VMind/blob/d4e0d4e7c1164c0ba01f70e8ba7f457b6f903c87/packages/vmind/src/core/VMind.ts#L126C31-L127C1
如果同时传入 theme 和 ColorPalate 参数如何处理呢

**Comment by da730** [comment]
> 似乎与目前已有的功能有一部分功能重合
> 
> https://github.com/VisActor/VMind/blob/d4e0d4e7c1164c0ba01f70e8ba7f457b6f903c87/packages/vmind/src/core/VMind.ts#L126C31-L127C1
> 
> 如果同时传入 theme 和 ColorPalate 参数如何处理呢

以theme为准，colorPalette参数只影响图表的配色（spec.colors），theme除此之外还会影响label样式、图例样式、背景色等

**Comment by Abyseas** [comment]
请问这个issue有人认领吗，没人的话我想认领一下
