### ISSUE TITLE
[Chart Generation] 支持自定义模型

### ISSUE THREAD

**Issue by da730** [VisActor/VMind#107]
1. 修改runApplication方法，当用户传入不支持的模型类型时，也可以采用默认策略执行任务

**Comment by hulijuan410** [comment]
mark

**Comment by MaxtuneLee** [comment]
> 1. runApplication

根据目前 `getModel` 的定义，如果用户输入了一个不存在的模型应该是会用的 `CHART-ADVISER`

https://github.com/VisActor/VMind/blob/d4e0d4e7c1164c0ba01f70e8ba7f457b6f903c87/packages/vmind/src/core/VMind.ts#L86C1-L93C4

按照上面 _model 初始化的意思是要将 `getModel` 的行为改为默认用 3.5 吗？

https://github.com/VisActor/VMind/blob/d4e0d4e7c1164c0ba01f70e8ba7f457b6f903c87/packages/vmind/src/core/VMind.ts#L35C5-L35C50

**Comment by da730** [comment]
sorry，可能没写清楚，我补充一下：
getModel新增一个custom类型的模型，图表生成、数据聚合在modelType=custom时使用skylark模型的流程。skylark方案会调用两次LLM，在能力弱于3.5的模型上效果比较好。后期会逐步淘汰gpt技术方案。
